# Generated by Django 5.1 on 2024-11-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_department_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='department',
            field=models.CharField(choices=[('Software Developer', 'Software Developer'), ('HR', 'HR'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Admin', 'Admin')], default='Software Developer', max_length=255),
        ),
    ]
