# Generated by Django 5.2.8 on 2026-01-18 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_attendance_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', 'employee__first_name'], 'verbose_name_plural': 'Attendances'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='department',
        ),
    ]
