# Generated by Django 5.2.8 on 2026-01-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_attendance_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(unique=True)),
                ('is_recurring', models.BooleanField(default=False, help_text='If checked, this holiday repeats every year on the same date')),
            ],
            options={
                'verbose_name_plural': 'Holidays',
                'ordering': ['date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_employee_date'),
        ),
    ]
